### ISSUE TITLE
Credential verification(Frontend)

### ISSUE THREAD

**Issue by tipusinghaw** [credebl/platform#11]
- [x] Add select schema page
 - [x] Add select credential-definition page
 - [x] Add select connection page
 - [x] Design select attributes and predicates page
 - [x] API integration  `Create proof request` for the verification page
 - [x] Remove `get schema by id ` API dependency
 - [x] Add schema and credential definition for verification restriction
 - [x] Error handling
 - [x] Design & Display verification list
 - [x] Integrate fetch proof request list GET API
 - [x] Integrate accept proof request POST API
 - [x] Integrate present-proof by id API

**Comment by ankita-p17** [comment]
Completed
