### ISSUE TITLE
Maintain a flag for multiple ecosystem for one org

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#169]
- [x] Created a `multiEcosystemSupport` flag in the ecosystem_config
- [x] Managed the APIs of create ecosystem and accept invitation for ecosystem for `multiEcosystemSupport`

- [x] Add a list of ecosystems
- [x] On Click of the ecosystem, show the dashboard for the created ecosystem
- [x] Create ecosystem profile card UI
- [x] Add select ecosystem option and handle UI elements according to Ecosystem ID and Role
- [x] Handle multi ecosystem flag throughout the application

**Comment by sanjay-k1910** [comment]
Completed.
