### ISSUE TITLE
refactor: APIs response refactor

### ISSUE THREAD

**Issue by KulkarniShashank** [credebl/platform#230]
Refactor the responses of APIs to avoid displaying unnecessary or confidential data to the user.
Replace the return type of object to adequately curated interfaces.

API Checklist:

- Change Promise<object> to a proper interface.
- Response refactor.
- Validation on Payload.
- Error Response.
- End-to-end testing.

APIs to refactor:

- [x] Get organization by Id 
- [x] Get organizations 
- [x] Get public Organizations 
- [x] Get Public Profile of an Organization 
- [x] Get Organization Recieved Invitations 
- [x] Get Organization Roles 
- [x] Get Organization Dashboard
- [x] Get Organization Profile
- [x] Get Org Invitations Pagination
- [x] Get Invitations By OrgId
- [x] Fetch Ecosystem Details
- [x] Fetch Ecosystem Org
- [x] Get Ecosystem Lead Details / Endorsement Requests
- [x] Create Ecosystem
- [x] Edit Ecosystem
- [x] Get all Ecosystems
- [x] Get Ecosystem Dashboard Details
- [x] Get Ecosystem Invitations
- [x] Fetch Ecosystem Members
- [x] Get invitations by orgId
- [x] Get endorsement Transactions
- [x] Get all Ecosystem Schemas
- [ ] Delete Ecosystem Invitations
- [ ] Schema Endorsement Request
- [ ] Cred-Def Endorsement Request
- [ ] Sign Endorsement Transaction
- [ ] Submit Endorsement Transaction
- [ ] Auto-Endorsement Transaction
- [ ] Decline Endorsement Transaction
- [x] Get User Profile
- [x] Get User Public Profile
- [x] Update User Profile
- [x] Get User by Supabase ID
- [x] Get User by mail
- [x] Get User Credentials by ID
- [x] Fetch User Invitation 
- [x] Find Org Users
- [x] Fetch Users
- [x] Check if Users exist
- [x] Add User
- [x] Get User Activity
- [x] Fetch Platform Settings

Document Link: https://docs.google.com/document/d/16hoaK7tJDuXHtKmi9QkJJqbXXll8FLAgJ1Bx9QHDjqg/edit

**Comment by pranalidhanavade** [comment]
This is completed.
