### ISSUE TITLE
Create organization ecosystem DB relation

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#313]
- [x] Map `ecosystem` and `organization` model
- [x] Refactor create ecosystem dto and query.
- [x] Refactor accept/ reject ecosystem invitation dto and query.
- [x] Refactor ecosystem members list GET API

**Comment by sunilbade** [comment]
As per the discussion with @nishad-ayanworks, the issue related to this task has been resolved.

**Comment by pranalidhanavade** [comment]
This is completed.
