### ISSUE TITLE
Add restriction of one ledger to Ecosystem

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#339]
Ecosystem organizations should have to be on the same ledger network so, endorsement transactions should perform smoothly. Restrict organization to join ecosystem if its ledger network is different.

- [x] Include `ledgers` column in the ecosystem model
- [x] Store ledger details while  create ecosystem.
- [x] Match org ledger network with ecosystem while accept ecosystem invitation.
- [x] Check if the `ledger` details present in `ecosystem` while sending invitation to join
- [x] Add details of ledger if not present in ecosystem.
- [x] Refactor edit ecosystem for ledger details
- [x] Fetch ledger details in ecosystem invitations GET API
- [x] Display network details in the ecosystem invitations (Frontend)

**Comment by sunilbade** [comment]
@nishad-ayanworks Network information is missing in the Email content.

**Comment by pranalidhanavade** [comment]
This task is done.
