### ISSUE TITLE
Improve error handling for APIs of User, Auth modules

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#353]
- Change the existing `Promise<object>` to a well-defined interface.
- Ensure that API routes are both self-explanatory and aligned with their respective functionalities.
- Refactor responses by populating only the necessary fields in the response.
- Implement RoleGuards for role-specific authentication to APIs.
- End-to-end testing.
- Check API status and status codes for consistency.
- Error logs should be there when necessary.
- ESLint rules should not be disabled unless necessary.
- Validation on Payload.

1. Apply `trim()` on payload.
2. Apply `toString()`, `toNumber()` datatypes properly to payloads.
3. Apply `toOptional()` if parameters are optionals.
4. Apply `notNull` for parameters of payloads if not optional.

- Error Response.
ex: 

```
{
  "message": "User friendly message",
  "error": "Some error description/error stack",
  "statusCode": 400,
}

```

User:
- [x] Fetch login user details
- [x] Get all platform and ecosystem settings
- [x] Update platform and ecosystem settings
- [x] Users activity
- [x] Organization invitations
- [x] Check user exist
- [x] Get user credentials by Id
- [x] Share user certificate
- [x] Update user profile
- [x] Store user password details

Auth:
- [x] Verify user’s email
- [x] Send verification email
- [x] Register new user to platform
- [x] Authenticate the user for the access

**Comment by pranalidhanavade** [comment]
This is completed.
