### ISSUE TITLE
Improve error handling for Ledger service

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#354]
- API routes should be self-explanatory & aligned with functionality.
- Change `Promise<object>` to an interface.
- Refactor responses (Only necessary fields should populate in response).
- Check status codes 
- Check role wise authentication to APIs with `RoleGuards`
- Check API `status` and `statusCode` should be checked properly.
- Error logs should be there where ever necessary. 
- End-to-end testing.
- Validation on Payload.

1. Apply `trim()` on payload.
2. Apply `toString()`, `toNumber()` datatypes properly to payloads.
3. Apply `toOptional()` if parameters are optionals.
4. Apply `notNull` for parameters of payloads if not optional.

- Error Response.

ex: 

```
{
  "message": "User friendly message",
  "error": "Some error description/error stack",
  "statusCode": 400,
}

```
Schema APIs
- [x] Create Schema
- [x] Refactor global exception handler
- [x] Get All Schemas
- [x] Get all credential definitions by schema id

**Comment by sunilbade** [comment]
Tested in the QA environment and changes look fine.
