### ISSUE TITLE
Allow user to delete organization invitations

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#359]
Acceptance Criteria:

Front-end
- [x] Implement UI
- [x] On click, show confirmation popup
- [x] Integrate API and handle response
- [x] If Error, then show an error message in the `Alert` component, and the list should stay as it is.
- [x] If Success, then show a success message and update the list.

Back-end
- [x] Implement relational tables and delete entries accordingly
- [x] Implement interfaces for payload, success and error response
- [x] Implement selective data in response

**Comment by sanjay-k1910** [comment]
Completed.
