### ISSUE TITLE
Implement sorting, searching, refresh button for the below tables

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#360]
Implementation of sorting, searching and refresh buttons for the tables below
- Front-end
- [x] Refactor table component and Error Messages
- [x] Table should contain Search, Sort, Pagination and Refresh Button
- [x] Connection List
- [x] Issued Credentials
- [x] Verified Credentials
- [x] Member List Ecosystem
- [x] History OOB
- [x] History Details OOB
- [x] Connection List ( Issuance )
- [x] Connection List ( verification )

Implementation of sorting, searching for the tables below
- Back-end
- [x] Connection List
- [x] Issued Credentials
- [x] Verified Credentials

**Comment by 16-karan** [comment]
Implementation of sorting, searching and refresh button for the below tables
- Connection List
- Member List
- Selected User List
- Cred Def List
- History List
- History Details List
- Issued Credentials
- Attributes List
- Verified Credentials

**Comment by sunilbade** [comment]
Tested in the QA environment and the change looks fine.
