### ISSUE TITLE
Keycloak setup for user Registration & Authentication

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#402]
- [x] Extract the data of supabase in Json format.
- [x] Create migration for `keycloakUserId` in the users table
- [x] Register users to keycloak through NestJs
- [x] Login users to get keycloak access token
- [x] Work on the `jwt-strategy` to validate `accessToken` of keycloak.
- [x] Fetch organization owner and return details for `@User` decorator details

**User Story:**
As a system administrator, I want to set up user registration and authentication in Keycloak to ensure a secure and user-friendly experience for individuals accessing our platform.

**Acceptance Criteria:**

1. **User Registration:**
- Given that I am a system administrator, I should be able to configure Keycloak to allow users to register for an account.
- Given the registration process, users should provide essential information such as username, email, and password.

2. **Email Verification:**
- Given a user registers, an email verification process should be implemented, ensuring the validity of the provided email address.
- Given the verification email is sent, users should receive clear instructions on how to verify their email address.

3. **Password Policies:**
- Given user registration, Keycloak should enforce strong password policies, including minimum length and complexity requirements.

4. **Authentication Methods:**
- Given registered users, Keycloak should support multiple authentication methods, including username/password, FIDO, and multi-factor authentication (MFA).

5. **Forgot Password Functionality:**
- Given a user forgets their password, Keycloak should provide a "Forgot Password" functionality.
- Given a password reset request, users should receive a secure email link allowing them to reset their password.

6. **Terms of Service and Privacy Policy:**
- Given user registration, Keycloak should provide the ability to present and enforce acceptance of terms of service and privacy policy during the registration process.

7. **Account Lockout Mechanism:**
- Given repeated failed login attempts, Keycloak should implement an account lockout mechanism to protect against brute-force attacks.

8. **User Profile Management:**
- Given successful authentication, users should be able to manage and update their profile information within Keycloak.

9. **Logging and Auditing:**
- Given user registration and authentication activities, Keycloak should log relevant information for auditing purposes, including successful and unsuccessful attempts.

10. **Secure Connection:**
- Given the sensitive nature of authentication, Keycloak should enforce secure connections (HTTPS) to protect data during transmission.

11. **Documentation:**
- Given the completion of the setup, comprehensive documentation should be provided for administrators and developers, covering the configuration, customization, and troubleshooting steps for user registration and authentication in Keycloak.

**Comment by sunilbade** [comment]
Tested on the QA environment and the changes look fine.
