### ISSUE TITLE
Script to migrate all existing users from to Keycloak

### ISSUE THREAD

**Issue by nishad-ayanworks** [credebl/platform#453]
- [x] Fetch all the existing users from supabase in JSON format
- [x] Write script to migrate all the users to keycloak
- [x] Implement bcrypt for password storage
- [x] Reset Password flow to migrate existing supabase users to keycloak (mid sprint)
- [x] Work on the Architechture diagram of login flow and reset password (mid sprint)
- [x] Work on the forgot password feature to reset new password (mid sprint)

**Comment by sunilbade** [comment]
Tested in the QA environment and changes look fine.
