### ISSUE TITLE
feat: handle notification on ADEYA

### ISSUE THREAD

**Issue by ankita-p17** [credebl/platform#459]
**User Story:**
As a user of the ADEYA mobile app, I want to receive push notifications to enhance my experience by staying updated on relevant information and events.

**Acceptance Criteria:**

1.  **Push Notification ON and OFF Feature:**
- Given that I am a user of the ADEYA mobile app, I should be presented with an option to ON or OFF of receiving push notifications from the ADEYA app.

2. **Notification Preferences:**
- Given that I have opted-in for push notifications, I should have the ability to customize my notification preferences within the ADEYA app, specifying the types of updates or events I want to be notified about.

3. **Permission Handling:**
- Given that push notifications are enabled, the ADEYA app should request the necessary permissions from me to send notifications, complying with the platform's guidelines for user consent.

4. **Real-time Updates:**
- Given that there is new and relevant information or events within the ADEYA app, I should receive push notifications in real time on my mobile device.

5. **Actionable Notifications:**
- Given that a push notification is received, there should be actionable elements (e.g., buttons) allowing me to perform quick actions directly from the notification without opening the ADEYA app. 

6. **Notification History:**
- Given that I may miss some notifications, the ADEYA app should maintain a notification history feature within the application for me to review previous alerts.

7. **Device Compatibility:**
- Given that I may use different devices (e.g., iOS, Android), push notifications from the ADEYA app should be compatible with the respective platform's notification system.

**Comment by tipusinghaw** [comment]
Completed
