### ISSUE TITLE
Required attributes in Create schema API (back-end)

### ISSUE THREAD

**Issue by pranalidhanavade** [credebl/platform#516]
- Change the Create Schema API to make at least one of the attributes compulsory.

**Acceptance Criteria**

- [x] User should be able to issue credentials with required attribute
- [x] Upon successful validation of input data, the API should create a new schema based on the provided attributes
- [x] If required attribute is missing, the API should return an appropriate error message indicating required attribute is missing

**Comment by sayali-chavan96** [comment]
Tested on the QA environment, it is working as expected
