### ISSUE TITLE
feat: Multi-select connection for issuance (FE/BE)

### ISSUE THREAD

**Issue by vivekayanworks** [credebl/platform#609]
**User story**
- User should be able to select single as well as multiple connections while creating offer, so that at a time credential offer request can be send to multiple connections.

**Acceptance Criteria**
- To add support for selection of multiple connections while Issuance

Back-end:
- [x] Changes in payload of POST `orgs/{orgId}/credentials/offer` API.
- [x] Implementation of multiple coonection selection functionality.
- [x] There should be configurable maximum limit for multi-connection credentials.
- [x] Error Handling

Front-end:
- [x] Implement multiselect connection functionality while creating offer
- [x] Modify UI for select connection page
- [x] Modify UI for issuance page in which we have to give multiple cards according to connections count which we have selected
- [x] Input field validations

**Comment by sayali-chavan96** [comment]
As retested on the QA environment, it is working as expected
