### ISSUE TITLE
feat: verification using email (front-end)

### ISSUE THREAD

**Issue by vivekayanworks** [credebl/platform#611]
**Acceptance Criteria**

- [ ] As an organization Owner, Admin, or Verifier : I am able to send verification emails to the users
- [ ] Users should be able to receive verification email
- [ ] Users should be able to scan the attached QR code with ADEYA
- [ ] After scanning the QR code, users should receive proof request notifications

**Comment by ak708** [comment]
Is this issue still open?

**Comment by pranalidhanavade** [comment]
Figma design and discussion is pending

**Comment by ak708** [comment]
@pranalidhanavade are you working on this issue? Do you need any help?

**Comment by pranalidhanavade** [comment]
This is duplicate task of task : https://github.com/orgs/credebl/projects/1/views/5?pane=issue&itemId=73952208
