### ISSUE TITLE
feat: add organizations into ecosystem (BE/FE)

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/platform#672]
**User Story:
- As an ecosystem lead, I should be able to add my organizations to my ecosystem.

Backend :

- [x]  Develop a POST API to add organizations to the Ecosystem
- [x] Modify a GET API to fetch all organizations by organization role
- [x] Error handling

Frontend:

- [x] Integrate GET API to get a list of owner organizations
- [x] Integrate POST API to add organizations in the ecosystem
- [x] Develop UI to show organization list
- [x] Provide functionality to select multiple organizations on multiple pages

**Comment by sayali-chavan96** [comment]
## Pending Todos:

### Backend
- [ ]  When attempting to add another user's organization to the ecosystem using their organization ID, there is a need for validation. If the provided organization ID does not match the user's own organization ID, the system should return a '403 Forbidden' status code with the message: 'You do not have access'

### Frontend
- [ ] When multiple organizations are selected to add in the Ecosystem and the page is refreshed, the previously selected checkboxes should be reset

- [ ] Error messages should  not be displayed after clicking the Refresh button.

**Comment by sayali-chavan96** [comment]
As retested on the QA environment, it is working as expected
