### ISSUE TITLE
feat: add option for create new DID and set primary DID (FE)

### ISSUE THREAD

**Issue by sanjay-k1910** [credebl/platform#677]
- [x] UI for DID list with create DID button
- [x] On click of the `Create DID` button, Show a popup with DID creation options
- [x] Add validation and conditions to select the DID Method
- [x] Add option to set primary DID
- [x] Integrate GET API to show a list of DIDs
- [x] Integrate POST API to create a new DID
- [x] Integrate POST API to set primary DID
- [x] Apply network specific validations while creating new DID
- [x] Error handling

**Comment by bhavanakarwade** [comment]
The functionality for this task is complete, but after deployment, the UI for this task was modified. Therefore, the UI will be updated in the next task.
