### ISSUE TITLE
feat: Implement w3c credential issuance by connection Id (BE)

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/platform#695]
- [x] Implement w3c credential issuance by connection Id. (Support multi select connections)

**Comment by sayali-chavan96** [comment]
## Pending Todos:
### Backend

- [ ] When issuing W3C credentials with a connection ID, validation is required. If the provided protocol version is invalid ("protocolVersion": "v1"), the system should return a '400 Bad Request' status code with the message:"Provided protocol version is not supported"

- [ ] Validation of attributes should be required.

- [ ] Requirement changed: need to change request payload.

**Comment by bhavanakarwade** [comment]
As per discussion with @GHkrishna, He has upcoming task for supporting AnonCreds. In that task, he will modify the payload body according to the credential type. Therefore, he will handle the protocol version validation as part of that task
