### ISSUE TITLE
feat: Validate attributes and W3C schema URL while issuance

### ISSUE THREAD

**Issue by vivekayanworks** [credebl/platform#700]
**Acceptance Criteria**

- When user initiate an issuance process, the system should compare the schema attributes with the provided attributes
- If the schema attributes and the provided attributes are not the same, the system should display a user-friendly message

**Comment by bhavanakarwade** [comment]
This task is completed on date(23/05/2024), but the payload for this task is modified on date (30/05/2024). Need to discuss

**Comment by bhavanakarwade** [comment]
I have updated this functionality according to new changes

**Comment by sayali-chavan96** [comment]
## Pending Todos:

### Backend

- [ ] When try to create an offer with mismatched schema attributes the system should return a '400, Bad Request ' status code

**Comment by bhavanakarwade** [comment]
This task is completed.
