### ISSUE TITLE
feat: Limit 10 organizations per user

### ISSUE THREAD

**Issue by vivekayanworks** [credebl/platform#702]
**User story:**

- User should be able to create only 10 organizations.

**Acceptance Criteria:**

- If the total number of organizations created by the user reaches 10, the "Create Organization" button should be disabled to prevent further organization creation.
- When a user creates a new organization, the system should count the total number of organizations created by that user.

**Comment by sayali-chavan96** [comment]
## Pending Todos:

### Frontend

- [ ] When a user clicks the create  button, the previous error message should not be displayed in the create organization popup
- [ ] The "Create" button should be disabled once the user has reached the limit of 10 organizations.
