### ISSUE TITLE
feat: On-prem agent setup

### ISSUE THREAD

**Issue by KulkarniShashank** [credebl/platform#711]
- Agent configuration in Instance

 
- Platform API
- [x] Validate parameters if 'on_premises' is set to true.
- [x] Store agent details in the 'org_agent' table.
- [x] Perform a health check on the agent to verify initialization status.
- [x] Encrypt the token and store it in the 'org_agent' table.

**Comment by sayali-chavan96** [comment]
Tested on the QA environment, it is working as expected
