### ISSUE TITLE
feat: support delete organization

### ISSUE THREAD

**Issue by tipusinghaw** [credebl/platform#741]
**Description**
Implement a feature to support the deletion of an organization. When an organization is deleted, all associated users should be deleted first, followed by the deletion of the organization itself. An audit record should be maintained for compliance and tracking purposes.

### Task Details
Ensure the audit logging system is operational and able to record user and organization deletions.

**Steps to Implement**

Add an API for deleting organizations that initiate the deletion of all invitations associated with the organization.
After successfully deleting all invitations, proceed to delete the organization.
Log the organization deletion in the audit trail with details including organization ID, deletion timestamp, and the user who performed the deletion.

**Error Handling**
Implement error handling to manage failures during the deletion process. If user deletion fails, ensure the organization deletion is not attempted.

**Comment by bhavanakarwade** [comment]
This task is already completed
