### ISSUE TITLE
feat: Delete references of organization

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/platform#749]
- [x] Implement database table for tracking deleted audit trails
- [x] Implement API to delete verification record
- [x] Implement API to delete issuance record
- [x] Implement API to delete connections
- [x] Implement API to count (connection, issuance, verification, ecosystem, users, invitations) 
- [x] Implement API to delete ecosystem members
- [x] Implement send email functionality to inform ecosystem members

**Comment by sayali-chavan96** [comment]
Tested on the QA environment, it is working as expected
