### ISSUE TITLE
feat: Create endpoints for fetch country,state and city

### ISSUE THREAD

**Issue by shitrerohit** [credebl/platform#786]
- [x] Create prisma-schema modal for Country, state and city
- [x] Create separate endpoints for fetching the Country, State and Cites
- [x] Set relationship between Geo-location tables and organization table
- [x] Refector org creation API according to organization prisma model.

**Comment by ganeshawle25** [comment]
created Geo-Location as separate service and module in API-Gateway. Implements all three apis and tested on local environment. Now PR in review state.

**Comment by sayali-chavan96** [comment]
## Pending Todos:
### Backend

- [ ] When trying to fetch details of all states associated with a given countryId and providing an invalid countryId, (eg. 1013212) there is a need for validation,the system should return a '404 Not Found' status code
- [ ] when details of all cities associated with a given countryId and stateId and providing a mismatched countryId and stateId there is a need for validation the system should return status code should be 404 Not Found

**Comment by sayali-chavan96** [comment]
Tested on QA environment and it's working as expected
