### ISSUE TITLE
refactor: get W3C schemas by schema id

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/platform#807]
- [x] Modify GET API for fetch schema details by schemaId (fetch W3C schema details by schema Id)
- [x] Modify GET API for fetch all schemas by orgId (made changes in that API which are required for Educreds)
- [x] Modify GET API for fetch all platform schemas (added filtering changes on schema type)
- [x] Refactored integration of GET API for fetch all platform schemas from UI side

**Comment by sayali-chavan96** [comment]
Tested on the QA environment, it is working as expected
