### ISSUE TITLE
feat: Implement W3C issuance (FE)

### ISSUE THREAD

**Issue by pranalidhanavade** [credebl/platform#820]
Implement W3C issuance with connections.
- [x] Implement W3C issuance with single and multiple connections.
- [x] Changes in astro routes for W3C issuance.
- [x] Refactor existing flow of issuance with connections.
- [x] Payload changes for W3C issuance.

Implement W3C issuance with email.
- [x] Implement W3C email-issuance.
- [x] Changes in astro routes for W3C issuance
- [x] Refactor existing flow of email-issuance.
- [x] Payload changes for W3C issuance.

Implement W3C bulk-issuance.

- [x] Refactor existing flow of bulk-issuance.
- [x] Implement payload changes in API for download and upload csv file for bulk issuance.

**Comment by ashwini-aher** [comment]
Tested and Working as expected, Thus changing the status to "Done".
