### ISSUE TITLE
feat: OOB verification using email (FE)

### ISSUE THREAD

**Issue by bhavanakarwade** [credebl/platform#900]
- [x] Integrate OOB verification API
- [x] Integrate fetch cred def details by cred def Id API
- [x] Implement Verification Dashboard (connection, email, bulk).
- [x] Create Astro routes for verification (email, connections, bulk).
- [x] Develop custom component for the dashboard (issuance and verification).
- [x] Develop custom component for the customizable check-boxes.
- [x] Implement schema and cred-def list screens for verification.
- [x] Refactor fetch schemas to support W3C schemas and restrict W3C flow in cred-def lists.
- [x] Handle conditions for Astro routes for Jsonld and Indy
- [x] Develop attributes list screen
- [x] Develop support multiple email Id's screen to create proof request
- [x] Develop payload for Indy and Jsonld type flow
- [x] Applied conditions for requested attributes and requested predicates
- [x] Test complete flow for Indy and Jsonld flow

**Comment by ashwini-aher** [comment]
As tested, The changes are as expected, Thus changing the status to "Done".
