### ISSUE TITLE
4.1: Multithreading in Mediator

### ISSUE THREAD

**Issue by prasadgkalamkar** [credebl/platform#923]
- Implement a worker thread approach to handle message load efficiently

**Comment by tipusinghaw** [comment]
I Understand the mediator flows and protocols, for multithreading need the payload in bulk (array of payload).

**Comment by tipusinghaw** [comment]
I tried utilizing the [Indicio](https://indicio.tech/handling-high-volume-verification-with-socketdock/) mediator; however, the mediator invitation did not generate.

**Comment by pranalidhanavade** [comment]
Closing as per @tipusinghaw 's comment above
